=head1 NAME

Optconfig - Parse options and config files

=head1 SYNOPSIS

   opt = Optconfig.new(domain, { 'file=s' => '/var/log/file',
                                 'force!' => false,
                                 'define=s%' => { } })

   File.open(opt['file'], 'w') { |fh| fh.puts "Log entry" }

=head1 DESCRIPTION

This module implements a common config file and command-line option parsing
interface, including Optconfig standard options, that is shared with the
Optconfig Perl module. See that module for details.

=head1 AUTHOR

Jeremy Brinkley, E<lt>jbrinkley@proofpoint.comE<gt>

=cut
